variables:
  #变量尽量定义在最前面，方便不同工程的修改
  APP_NAME: 'ym-station'
  TARGET_DIR: 'dist'
  RELEASE_GITADDR: 'ssh://git@g.hz.netease.com:22222/qiye/release/ym-station.git'
   #本地发布目录
  DEPLOY_BASE_DIR: '/home/appops/pre-publish'
  #初始化本地发布目录
  INIT_DEPLOY_DIR_CMD: 'git clone $RELEASE_GITADDR $APP_NAME && cd $APP_NAME && ls -a && git config user.email "qiye_deploy@corp.netease.com" && git config user.name "qiye_deploy"'
   #获取项目最后提交说明
  COMMIT_LOG_CMD: 'git log -n 1 --pretty=format:"%h|%s|%cn|%cd" --date=short'

stages:
  - build
  - deploy
  - publish

# 运行
build-test:
    stage: build
    script:
    - pwd
    - npm i
    - npm run dev
    tags:
        - qiye-online-runner-new-2
    artifacts:
      paths:
        - dist
      expire_in: 1 days
    only:
        - master
        - dev
# 部署文件 将doc下的文件=》
deploy-test-2:
    stage: deploy
    script:
      - pwd
      - rsync -av doc/ /data/ym.163.com
    tags:
      - qiye-test-2-hz-new-2
    when: on_success
    environment:
      name: test
    only:
      - dev
      - master

#打包提交发布库
publish-online:
  stage: publish
  script:
    - pwd
    - currentPath=$(pwd)
    - ls -lh $currentPath/dist/
    - commit_msg=$($COMMIT_LOG_CMD) && echo $commit_msg
    - mkdir -p $DEPLOY_BASE_DIR && cd $DEPLOY_BASE_DIR
    - if [ ! -d "$APP_NAME" ];then
    - eval $INIT_DEPLOY_DIR_CMD
    - else
    - cd $APP_NAME && git pull && ls -a
    - fi
    
    - rsync -av --delete  --exclude '.git' $currentPath/$TARGET_DIR/ ./
    - cp $currentPath/$TARGET_DIR/index.html ./
    # - eval $PUSH_TO_RELEASE_REPO_CMD
    - git add -A && git commit -m "$commit_msg" && git push origin master
  tags:
    - qiye-online-runner-new-2
  when: manual
  environment:
    name: online
  only:
    - master


